timestamps: timestamps.c
	gcc timestamps.c -o bin/stampme -Wall -Werror -g

longestline: longestline.c
	gcc longestline.c -o bin/longme -Wall -Werror

string_sort: string_sort.c
	gcc string_sort.c -o bin/stringme -Wall -Werror

bubble_string_sort: bubble_string_sort.c
	gcc bubble_string_sort.c -o bin/bubbleme -Wall -Werror

dynamic_arrays: dynamic_arrays.c
	gcc dynamic_arrays.c -o bin/dynamicme -Wall -Werror

dynamic_string_arrays: dynamic_string_arrays.c
	gcc dynamic_string_arrays.c -o bin/dystringme -Wall -Werror

2D_arr_dynamic: 2D_arr_dynamic.c
	gcc 2D_arr_dynamic.c -o bin/2Dme -Wall -Werror

resize_dynamic: resize_dynamic.c
	gcc resize_dynamic.c -o bin/resizeme -Wall -Werror

2nd_string: 2nd_string.c
	gcc 2nd_string.c -o bin/2ndme -Wall -Werror
